[package]
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
categories = ["asynchronous", "development-tools::testing"]
description = "Cucumber testing framework for Rust, with async support. Fully native, no external test runners or dependencies."
documentation = "https://docs.rs/cucumber_rust"
edition = "2018"
homepage = "https://github.com/bbqsrc/cucumber-rust"
keywords = ["cucumber", "testing", "bdd", "atdd", "async"]
license = "MIT OR Apache-2.0"
name = "cucumber_rust"
readme = "README.md"
repository = "https://github.com/bbqsrc/cucumber-rust"
version = "0.8.4"

[features]
macros = ["cucumber_rust_codegen", "inventory"]

[dependencies]
async-stream = "0.3.0"
async-trait = "0.1.40"
clap = "2.33"
cute_custom_default = "2.1.0"
futures = "0.3.5"
futures-timer = "3.0.2"
gherkin = {package = "gherkin_rust", version = "0.10"}
globwalk = "0.8.0"
pathdiff = "0.2.0"
regex = "1.3.9"
shh = "1.0.1"
termcolor = "1.1.0"
textwrap = {version = "0.12.1", features = ["terminal_size"]}
thiserror = "1.0.20"
tracing = "0.1.25"
serde = "1.0.130"
serde_json = "1.0.67"

# Codegen dependencies
cucumber_rust_codegen = {version = "0.1", path = "./codegen", optional = true}
inventory = {version = "0.1", optional = true}
once_cell = "1.7.0"

[dev-dependencies]
capture-runner = {path = "tests/fixtures/capture-runner"}
serial_test = "0.5.0"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
tracing-subscriber = {version = "0.2.16", features = ["fmt"]}

[[test]]
harness = false
name = "cucumber_builder"

[[test]]
edition = "2018"
harness = true
name = "integration_test"

[workspace]
default-members = [".", "codegen"]
members = ["codegen", "tests/fixtures/capture-runner"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
